version: '3.7'

services:
  redis:
    image: redis:alpine
    # ports:
    #   - "6379:6379"
    command: redis-server --requirepass $REDIS_PASSWORD --appendonly yes
    environment:
      - REDIS_PASSWORD=$REDIS_PASSWORD
    volumes:
      - redis-data:/data
  
  bot:
    image: saintpa/dvpntipbot:latest
    command: npm run start
    environment:
      - BOT_TOKEN=$BOT_TOKEN
      - REDIS_URI=$REDIS_URI
    # volumes:
    #   - ./source:/build/source

volumes:
  redis-data: