version: '3'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server --requirepass $REDIS_PASSWORD --appendonly yes
    environment:
      - REDIS_PASSWORD=$REDIS_PASSWORD
    volumes:
      - redis-data:/data

volumes:
  redis-data: